# Generated by Django 2.0.4 on 2019-05-21 22:42 

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtmfInput',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
            ],
            options={
                'verbose_name': 'DTMF Element',
            },
            bases=('service_development.voiceserviceelement',),
        ),
    ]
