# Generated by Django 2.0.4 on 2019-05-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0003_dtmfinput__redirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtmfUserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_dtmf', to='service_development.UserInputCategory', verbose_name='Category')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_dtmf', to='service_development.CallSession')),
            ],
            options={
                'verbose_name': 'DTMF User Input',
            },
        ),
        migrations.AddField(
            model_name='dtmfinput',
            name='input_category',
            field=models.ForeignKey(blank=True, help_text='The category under which the input will be stored in the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtmf_input_category', to='service_development.UserInputCategory', verbose_name='Input category'),
        ),
    ]
