# Generated by Django 2.0.4 on 2019-05-22 20:23 

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0004_auto_20190522_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_type', models.CharField(choices=[('RE', 'Rice'), ('CN', 'Cotton'), ('SM', 'Sorghum')], default='RE', max_length=2)),
                ('amount_of_seeds', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('days_online', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(1)])),
                ('telephone_number', models.CharField(max_length=100)),
                ('location', models.ForeignKey(help_text="Recording of the offer's location", null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_development.SpokenUserInput', verbose_name='Offer location')),
            ],
        ),
        migrations.AddField(
            model_name='messagepresentation',
            name='execute_script',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
