# Generated by Django 2.0.4 on 2019-05-23 02:51 

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0005_auto_20190522_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedoffer',
            name='seeds_price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
