# Generated by Django 2.0.4 on 2019-05-23 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0006_seedoffer_seeds_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedoffer',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
