# Generated by Django 2.0.4 on 2019-05-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0008_messagepresentation_redirect_to_executed_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtmfinput',
            name='ask_confirmation',
            field=models.BooleanField(default=True, verbose_name='Ask the caller to confirm their input'),
        ),
        migrations.AddField(
            model_name='dtmfinput',
            name='ask_confirmation_voice_label',
            field=models.ForeignKey(blank=True, help_text='The voice label that asks the user to confirm their input. Example: "Are you satisfied with your input? Press 1 to confirm, or press 2 to retry."', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtfm_confirmation_voice_label', to='service_development.VoiceLabel', verbose_name='Ask for confirmation voice label'),
        ),
        migrations.AddField(
            model_name='dtmfinput',
            name='final_voice_label',
            field=models.ForeignKey(blank=True, help_text='The voice label that is played when the user has completed the input process. Example: "Thank you for your message! The input has been stored successfully."', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtfm_final_voice_label', to='service_development.VoiceLabel', verbose_name='Final voice label'),
        ),
        migrations.AddField(
            model_name='dtmfinput',
            name='repeat_recording_to_caller',
            field=models.BooleanField(default=True, verbose_name='Repeat the input to the caller before asking for confirmation'),
        ),
        migrations.AddField(
            model_name='dtmfinput',
            name='repeat_voice_label',
            field=models.ForeignKey(blank=True, help_text='The voice label that is played after the system repeats the user input. Example: "...dollars per bag of seeds."', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtfm_repeat_voice_label', to='service_development.VoiceLabel', verbose_name='Repeat input voice label'),
        ),
    ]
