# Generated by Django 2.0.4 on 2019-05-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0009_auto_20190524_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedoffer',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio File for web.', null=True, upload_to='', verbose_name='Audio'),
        ),
    ]
